/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagementsystem;


import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author dennis
 */
public class Menu_page extends javax.swing.JFrame {

    /**
     * Creates new form Menu_page
     */
    public Menu_page() {
        initComponents();
    }
    int [] cartCounter={0,0,0,0,0,0};
    static ArrayList<String> foodsList = new ArrayList<String>(); 
    static ArrayList<Integer> foodsQuantity = new ArrayList<Integer>();
    static HashMap<String,Integer> foods = new HashMap<String,Integer>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chapatiBeans = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        githeri = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ugaliBeans = new javax.swing.JButton();
        panel5 = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ugaliMatumbo = new javax.swing.JButton();
        panel4 = new java.awt.Panel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ugaliNdengu = new javax.swing.JButton();
        customerName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cartNo = new javax.swing.JLabel();
        foodCart = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/hotelImages/chapobeans.jpeg"))); // NOI18N

        jLabel3.setText("chapati beans");

        jLabel4.setText("ksh50");

        chapatiBeans.setText("add");
        chapatiBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapatiBeansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(117, 117, 117)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(chapatiBeans)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(chapatiBeans))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/hotelImages/githeri.jpeg"))); // NOI18N

        jLabel9.setText("Githeri");

        jLabel10.setText("ksh40");

        githeri.setText("add");
        githeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(githeri))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(githeri)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/hotelImages/ugalibeans.jpeg"))); // NOI18N

        jLabel6.setText("ugali beans");

        jLabel7.setText("ksh60");

        ugaliBeans.setText("add");
        ugaliBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugaliBeansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(ugaliBeans))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(ugaliBeans)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/hotelImages/ugalimatumbo.jpeg"))); // NOI18N

        jLabel15.setText("ugali matumbo");

        jLabel16.setText("ksh70");

        ugaliMatumbo.setText("add");
        ugaliMatumbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugaliMatumboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(ugaliMatumbo))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(ugaliMatumbo))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/hotelImages/ugalindengu.jpeg"))); // NOI18N

        jLabel12.setText("ugali ndengu");

        jLabel13.setText("ksh80");

        ugaliNdengu.setText("add");
        ugaliNdengu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugaliNdenguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(ugaliNdengu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(ugaliNdengu))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jScrollPane1.setViewportView(jPanel1);

        customerName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        customerName.setText("Guest");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        cartNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cartNo.setText("0");
        jPanel2.add(cartNo);
        cartNo.setBounds(100, 40, 60, 25);

        foodCart.setText("Foodcart");
        foodCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCartActionPerformed(evt);
            }
        });
        jPanel2.add(foodCart);
        foodCart.setBounds(20, 13, 120, 50);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(756, 756, 756))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(customerName)
                        .addComponent(jLabel17))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chapatiBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapatiBeansActionPerformed
        // TODO add your handling code here:
        if(cartCounter[0]==0){
            changeCartNo();
            foodsList.add("Chapati Beans");
            foodsQuantity.add(1);
            foods.put("Chapati Beans",50);
            System.out.println(foods);
            cartCounter[0]++;
        } 
        
    }//GEN-LAST:event_chapatiBeansActionPerformed

    private void foodCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCartActionPerformed
        // TODO add your handling code here:
        CartFrame b=new CartFrame();
        b.foodname1.setVisible(false);
         b.foodname2.setVisible(false);
         b.foodname3.setVisible(false);
         b.foodname4.setVisible(false);
         b.foodname5.setVisible(false);
         b.quantity1.setVisible(false);
         b.quantity2.setVisible(false);
         b.quantity3.setVisible(false);
         b.quantity4.setVisible(false);
         b.quantity5.setVisible(false);
         b.plus1.setVisible(false);
         b.plus2.setVisible(false);
         b.plus3.setVisible(false);
         b.plus4.setVisible(false);
         b.plus5.setVisible(false);
         b.minus1.setVisible(false);
         b.minus2.setVisible(false);
         b.minus3.setVisible(false);
         b.minus4.setVisible(false);
         b.minus5.setVisible(false); 
         b.price1.setVisible(false);
         b.price2.setVisible(false);
         b.price3.setVisible(false);
         b.price4.setVisible(false);
         b.price5.setVisible(false);
        if(foods.size()==1){
            b.foodname1.setVisible(true);
            b.quantity1.setVisible(true);
            b.plus1.setVisible(true);
            b.minus1.setVisible(true);
            b.price1.setVisible(true);
            b.foodname1.setText(foodsList.get(0));
            int foodkey=foods.get(foodsList.get(0));
            b.price1.setText(Integer.toString(foodkey));
            b.quantity1.setText("1");
            b.totalPrice.setText(Integer.toString(foodkey));
            
        }
        else if(foods.size()==2){
            int [] prices={0,0};
            b.foodname1.setVisible(true);
            b.quantity1.setVisible(true);
            b.plus1.setVisible(true);
            b.minus1.setVisible(true);
            b.foodname2.setVisible(true);
            b.quantity2.setVisible(true);
            b.plus2.setVisible(true);
            b.minus2.setVisible(true);
            b.price1.setVisible(true);
            b.price2.setVisible(true);
            b.foodname1.setText(foodsList.get(0));
            int foodkey=foods.get(foodsList.get(0));
            prices[0]=foodkey;
            b.price1.setText(Integer.toString(foodkey));
            b.quantity1.setText("1");
            b.foodname2.setText(foodsList.get(1));
            foodkey=foods.get(foodsList.get(1));
            prices[1]=foodkey;
            b.price2.setText(Integer.toString(foodkey));
            b.quantity2.setText("1");
            int totalPrice=prices[0]+prices[1];
            b.totalPrice.setText(Integer.toString(totalPrice));
        }
        else if(foods.size()==3){
            int []prices={0,0,0};
             b.foodname1.setVisible(true);
            b.quantity1.setVisible(true);
            b.plus1.setVisible(true);
            b.minus1.setVisible(true);
            b.foodname2.setVisible(true);
            b.quantity2.setVisible(true);
            b.plus2.setVisible(true);
            b.minus2.setVisible(true);
            b.foodname3.setVisible(true);
            b.quantity3.setVisible(true);
            b.plus3.setVisible(true);
            b.minus3.setVisible(true);
            b.price1.setVisible(true);
            b.price2.setVisible(true);
            b.price3.setVisible(true);
            b.foodname1.setText(foodsList.get(0));
            int foodkey=foods.get(foodsList.get(0));
            prices[0]=foodkey;
            b.price1.setText(Integer.toString(foodkey));
            b.quantity1.setText("1");
            b.foodname2.setText(foodsList.get(1));
            foodkey=foods.get(foodsList.get(1));
            prices[1]=foodkey;
            b.price2.setText(Integer.toString(foodkey));
            b.quantity2.setText("1");
            b.foodname3.setText(foodsList.get(2));
            foodkey=foods.get(foodsList.get(2));
            prices[2]=foodkey;
            b.price3.setText(Integer.toString(foodkey)); 
            b.quantity3.setText("1");
            int totalPrice=0;
            for(int i=0;i<prices.length;i++){
                totalPrice+=prices[i];
            }
            b.totalPrice.setText(Integer.toString(totalPrice));
        }
        else if(foods.size()==4){
            int []prices={0,0,0,0};
             b.foodname1.setVisible(true);
            b.quantity1.setVisible(true);
            b.plus1.setVisible(true);
            b.minus1.setVisible(true);
            b.foodname2.setVisible(true);
            b.quantity2.setVisible(true);
            b.plus2.setVisible(true);
            b.minus2.setVisible(true);
            b.foodname3.setVisible(true);
            b.quantity3.setVisible(true);
            b.plus3.setVisible(true);
            b.minus3.setVisible(true);
            b.foodname4.setVisible(true);
            b.quantity4.setVisible(true);
            b.plus4.setVisible(true);
            b.minus4.setVisible(true);
            b.price1.setVisible(true);
            b.price2.setVisible(true);
            b.price3.setVisible(true);
            b.price4.setVisible(true);
            b.foodname1.setText(foodsList.get(0));
            int foodkey=foods.get(foodsList.get(0));
            prices[0]=foodkey;
            b.price1.setText(Integer.toString(foodkey));
            b.quantity1.setText("1");
            b.foodname2.setText(foodsList.get(1));
            foodkey=foods.get(foodsList.get(1));
            prices[1]=foodkey;
            b.price2.setText(Integer.toString(foodkey));
            b.quantity2.setText("1");
            b.foodname3.setText(foodsList.get(2));
            foodkey=foods.get(foodsList.get(2));
            prices[2]=foodkey;
            b.price3.setText(Integer.toString(foodkey)); 
            b.quantity3.setText("1");
            b.foodname4.setText(foodsList.get(3));
            foodkey=foods.get(foodsList.get(3));
            prices[3]=foodkey;
            b.price4.setText(Integer.toString(foodkey)); 
            b.quantity4.setText("1");
            int totalPrice=0;
            for(int i=0;i<prices.length;i++){
                totalPrice+=prices[i];
            }
            b.totalPrice.setText(Integer.toString(totalPrice));
        }
        else if(foods.size()==5){
            int [] prices={0,0,0,0,0};
             b.foodname1.setVisible(true);
            b.quantity1.setVisible(true);
            b.plus1.setVisible(true);
            b.minus1.setVisible(true);
            b.foodname2.setVisible(true);
            b.quantity2.setVisible(true);
            b.plus2.setVisible(true);
            b.minus2.setVisible(true);
            b.foodname3.setVisible(true);
            b.quantity3.setVisible(true);
            b.plus3.setVisible(true);
            b.minus3.setVisible(true);
            b.foodname4.setVisible(true);
            b.quantity4.setVisible(true);
            b.plus4.setVisible(true);
            b.minus4.setVisible(true);
            b.foodname5.setVisible(true);
            b.quantity5.setVisible(true);
            b.plus5.setVisible(true);
            b.minus5.setVisible(true);
            b.price1.setVisible(true);
            b.price2.setVisible(true);
            b.price3.setVisible(true);
            b.price4.setVisible(true);
            b.price5.setVisible(true);
            b.foodname1.setText(foodsList.get(0));
            int foodkey=foods.get(foodsList.get(0));
            prices[0]=foodkey;
            b.price1.setText(Integer.toString(foodkey));
            b.quantity1.setText("1");
            b.foodname2.setText(foodsList.get(1));
            foodkey=foods.get(foodsList.get(1));
            prices[1]=foodkey;
            b.price2.setText(Integer.toString(foodkey));
            b.quantity2.setText("1");
            b.foodname3.setText(foodsList.get(2));
            foodkey=foods.get(foodsList.get(2));
            prices[2]=foodkey;
            b.price3.setText(Integer.toString(foodkey)); 
            b.quantity3.setText("1");
            b.foodname4.setText(foodsList.get(3));
            foodkey=foods.get(foodsList.get(3));
            prices[3]=foodkey;
            b.price4.setText(Integer.toString(foodkey)); 
            b.quantity4.setText("1");
            b.foodname5.setText(foodsList.get(4));
            foodkey=foods.get(foodsList.get(4));
            prices[4]=foodkey;
            b.price5.setText(Integer.toString(foodkey)); 
            b.quantity5.setText("1");
            int totalPrice=0;
            for(int i=0;i<prices.length;i++){
                totalPrice+=prices[i];
            }
            b.totalPrice.setText(Integer.toString(totalPrice));
        }
        b.setVisible(true);   
    }//GEN-LAST:event_foodCartActionPerformed

    private void ugaliMatumboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugaliMatumboActionPerformed
        // TODO add your handling code here:
        if(cartCounter[1]==0){
            changeCartNo();
            foodsList.add("Ugali Matumbo");
            foodsQuantity.add(1);
            foods.put("Ugali Matumbo",70);
            cartCounter[1]++;
        } 
    }//GEN-LAST:event_ugaliMatumboActionPerformed

    private void githeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githeriActionPerformed
        // TODO add your handling code here:
        if(cartCounter[2]==0){
            changeCartNo();
            foodsList.add("Githeri");
            foodsQuantity.add(1);
            foods.put("Githeri",40);
            cartCounter[2]++;
        } 
    }//GEN-LAST:event_githeriActionPerformed

    private void ugaliNdenguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugaliNdenguActionPerformed
        // TODO add your handling code here:
        if(cartCounter[3]==0){
            changeCartNo();
            foodsList.add("Ugali Ndengu");
            foodsQuantity.add(1);
            foods.put("Ugali Ndengu",80);
            System.out.println(foods);
            cartCounter[3]++;
        } 
    }//GEN-LAST:event_ugaliNdenguActionPerformed

    private void ugaliBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugaliBeansActionPerformed
        // TODO add your handling code here:
        if(cartCounter[4]==0){
            changeCartNo();
            foodsList.add("Ugali Beans");
            foodsQuantity.add(1);
            foods.put("Ugali Beans",60);
            System.out.println(foods);
            cartCounter[4]++;
        } 
    }//GEN-LAST:event_ugaliBeansActionPerformed
    public void changeCartNo(){
          if(cartNo.getText()=="0"){
            cartNo.setText("1");
        }
        else{
            int numberCart=Integer.parseInt(cartNo.getText());
            numberCart++;
            cartNo.setText(Integer.toString(numberCart));  
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartNo;
    private javax.swing.JButton chapatiBeans;
    public javax.swing.JLabel customerName;
    private javax.swing.JButton foodCart;
    private javax.swing.JButton githeri;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private javax.swing.JButton ugaliBeans;
    private javax.swing.JButton ugaliMatumbo;
    private javax.swing.JButton ugaliNdengu;
    // End of variables declaration//GEN-END:variables
}
